[workspace]
channels = ["conda-forge", "auto-mech"]
name = "PES Playground"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
autochem = ">=0.2025.0,<0.2026"
ipykernel = ">=7.1.0,<8"
python = "<3.14"
rdkit = ">=2025.9.4,<2026"
networkx = ">=3.6.1,<4"

[pypi-dependencies]
hyperqueue = ">=0.24.0, <0.25"